### ISSUE TITLE
from and into parallel iterators

### ISSUE THREAD

**Issue by hoodie** [havarnov/multimap#18]
Hi there, I'm just playing around with rayon and noticed that you cannot collect into a Multimap from a ParallelIterator. It would be great to add these implementations.

**Comment by havarnov** [comment]
Hi. Sorry for the late answer. I don't think we should introduce Rayon as a dependancy for the Multimap crate.

Two options:
* make a wrapper struct for Multimap and impl this functionality for the wrapper struct.
* add Rayon as a optional dependancy.

Do you think option 1 is good enough for your use case?

**Comment by hoodie** [comment]
My original idea was option two, similar to how many crates have a serde feature. How ever wouldn't this require a wrapper anyway? I haven't looked closely how this would be implemented
