### ISSUE TITLE
Method to get the total number of elements in a MultiMap

### ISSUE THREAD

**Issue by sitaktif** [havarnov/multimap#26]
The `len()` method returns the number of distinct keys in the MultiMap.

It would be great to have a method (maybe called `len_all()` for consistency with `iter_all()`?) that returns the number of values in the MultiMap.

**Comment by sitaktif** [comment]
Current workaround looks like this:

```rust
my_multimap.iter_all().fold(0, |acc, (_, values)| acc + values.len())
```

Though I'd be interested to know if there is a nicer way :-)

**Comment by mocsy** [comment]
What if `keys_len()` would return what `len()` does today, and `len()` would return the total `len`?
```rust
fn len(&self) -> usize {
   self.iter_all().fold(0, |acc, (_, values)| acc + values.len())
}
```
(Or maybe a more efficient implementation would be possible.)

**Comment by sitaktif** [comment]
I didn't want to suggest introducing breaking changes but I would also find your suggestion more intuitive @mocsy

**Comment by havarnov** [comment]
I think it make more sense with ```MultiMap::len()``` returns number of keys, but I might be the odd one out.

Anyways, what if we provide a new method for getting the total number of values which can be introduced without breaking backwards compatability? And then maybe switch them around in a possible mayor version update?

PS. Sry for late reply, thanks for being patient 👍
