### ISSUE TITLE
remove, remove_all or remove_first, remove

### ISSUE THREAD

**Issue by mocsy** [havarnov/multimap#28]
```rust
pub fn remove<Q: ?Sized>(&mut self, k: &Q) -> Option<Vec<V>>
where
    K: Borrow<Q>,
    Q: Eq + Hash, 
Removes a key from the map, returning the vector of values at the key if the key was previously in the map.
```
The ability to remove the first value for a key would be great.

If you'd want this to look like more closely as `HashMap` does:
Remove would return the first element and could have the same interface as HashMap:
```rust
pub fn remove<Q: ?Sized>(&mut self, k: &Q) -> Option<V>
where
    K: Borrow<Q>,
    Q: Hash + Eq, 
Removes a key from the map, returning the value at the key if the key was previously in the map.
```
And the current function would be renamed to `remove_all`.

I'm fine with having a new function named remove_first (or remove_one or remove_next as you like) instead.

On that note maybe removing the last one would be useful as well.

**Comment by mocsy** [comment]
Also HashMap has this:
```rust
pub fn remove_entry<Q: ?Sized>(&mut self, k: &Q) -> Option<(K, V)>
where
    K: Borrow<Q>,
    Q: Hash + Eq, 
Removes a key from the map, returning the stored key and value if the key was previously in the map.
```
This could remove the `Entry` where the key and the value matches and keep the other values associated with the key.

**Comment by havarnov** [comment]
I like the idea of a ```remove_first```. And also ```remove_entry```. PR is appreciated!
