### ISSUE TITLE
Need from_iter implementation from Iterator of Vec<V>

### ISSUE THREAD

**Issue by AATruttse** [havarnov/multimap#47]
Need from_iter implementation from Iterator of Vec<V> to construct multimap from iterator of Vec<V> - for example, for collecting multimap from iterator of Vec<V> filtered from other multimap.

I already wrote it. How can I propose to contribute this code?

**Comment by havarnov** [comment]
Open a PR?

**Comment by AATruttse** [comment]
> Open a PR?

Done!
https://github.com/havarnov/multimap/pull/48

**Comment by AATruttse** [comment]
Thank you very much, fixed this fmt errors!

**Comment by havarnov** [comment]
Thank you! Release in version 0.10.0 https://crates.io/crates/multimap

**Comment by SamirTalwar** [comment]
Heya, v0.10.0 doesn't seem to have made it into the changelog or _Cargo.toml_ in this repository (though they do seem to be there in [the source referenced by docs.rs](https://docs.rs/crate/multimap/0.10.0/source/)). Are there any plans to push?

**Comment by havarnov** [comment]
Sry, pushed the changes now! Probably a reminder that I should push to crates.io from githib actions :|
